Controllers/ManejoReporteController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using NuevoHogar.Utils;
using NuevoHogar.ModeloDTO;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;

namespace NuevoHogar.Controllers;

public class ManejoReporteController : Controller{
    private readonly IHttpClientFactory? _IhttpClientFactory;
    public ManejoReporteController(IHttpClientFactory httpClientFactory){
        _IhttpClientFactory = httpClientFactory;
    }
    
    public IActionResult GenerarReporte(){
        try{
            return View();
        }catch(Exception ex){
            return RedirectToAction("ErrorPagina", "Home");
        }
    }

    public async System.Threading.Tasks.Task<IActionResult> EditReporte(string? s){
        Reporte2DTO reporteAux = new Reporte2DTO();
        ReporteDTO reporte = new ReporteDTO();
        try{
            var cliente = _IhttpClientFactory?.CreateClient("BackEnd");
            cliente?.DefaultRequestHeaders.Clear();
            cliente?.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            var mensaje = await cliente?.GetAsync("api/reportes/" + s)!;

            if(mensaje.IsSuccessStatusCode){
                string cadena = mensaje.Content.ReadAsStringAsync().Result;
                reporteAux = JsonConvert.DeserializeObject<Reporte2DTO>(cadena);
                System.Console.WriteLine(reporteAux.idReporteDeMaltrato);
            }
            reporte = convertirReporte(reporteAux);
            return View(reporte);
        }catch(Exception ex){
            return RedirectToAction("ErrorPagina", "Home");
        }
    }

    private ReporteDTO convertirReporte(Reporte2DTO r){
        ReporteDTO reporte = new ReporteDTO();
        reporte.idReporteDeMaltrato = r.idReporteDeMaltrato;
        reporte.ubicacion = r.ubicacion;
        reporte.descripcion = r.descripcion;
        reporte.fecha = r.fecha;
        reporte.idRefugio = r.idRefugio;
        reporte.idUsuario = r.idUsuario;
        return reporte;
    }

    public async System.Threading.Tasks.Task<IActionResult> ListaReportesUsuario(){
        List<Reporte2DTO> listaReportes = new List<Reporte2DTO>();
        List<Reporte2DTO> listaFiltrada = new List<Reporte2DTO>();
        try{
            var cliente = _IhttpClientFactory?.CreateClient("BackEnd");
            cliente?.DefaultRequestHeaders.Clear();
            cliente?.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            var mensaje = await cliente?.GetAsync("api/reportes/lastReports/20")!;

            System.Console.WriteLine(mensaje.ToString());

            if(mensaje.IsSuccessStatusCode){
                string listaStrings = mensaje.Content.ReadAsStringAsync().Result;
                listaReportes = JsonConvert.DeserializeObject<List<Reporte2DTO>>(listaStrings);
            }

            foreach(Reporte2DTO r in listaReportes){
                if(r.idUsuario == Cliente.Usuario.IdUsuario)
                    listaFiltrada.Add(r);
            }

            return View(listaFiltrada);
        }catch(Exception ex){
            return RedirectToAction("ErrorPagina", "Home");
        }
    }

    public async System.Threading.Tasks.Task<IActionResult> ListaReportes(){
        List<Reporte2DTO> listaReportes = new List<Reporte2DTO>();
        try{
            var cliente = _IhttpClientFactory?.CreateClient("BackEnd");
            cliente?.DefaultRequestHeaders.Clear();
            cliente?.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            var mensaje = await cliente?.GetAsync("api/reportes/lastReports/20")!;

            System.Console.WriteLine(mensaje.ToString());

            if(mensaje.IsSuccessStatusCode){
                string listaStrings = mensaje.Content.ReadAsStringAsync().Result;
                listaReportes = JsonConvert.DeserializeObject<List<Reporte2DTO>>(listaStrings);
            }

            return View(listaReportes);
        }catch(Exception ex){
            return RedirectToAction("ErrorPagina", "Home");
        }
    }

    public async System.Threading.Tasks.Task<IActionResult> GenerarReporteBtn(ReporteDTO reporteAux){
        try{
            System.Console.WriteLine(reporteAux.fecha);
            reporteAux.idUsuario = Cliente.Usuario.IdUsuario;
            reporteAux.idRefugio = null;
            reporteAux.idReporteDeMaltrato = Guid.NewGuid().ToString();
            System.Console.WriteLine(reporteAux.idReporteDeMaltrato);

            DefaultContractResolver contractResolver = new DefaultContractResolver{

                NamingStrategy = new CamelCaseNamingStrategy()

            };

            string json = JsonConvert.SerializeObject(reporteAux, new JsonSerializerSettings{

                ContractResolver = contractResolver,
                Formatting = Formatting.Indented

            });

            System.Console.WriteLine(json);

            var data = new StringContent(json, Encoding.UTF8, "application/json");
            var cliente = _IhttpClientFactory?.CreateClient("BackEnd");
            cliente?.DefaultRequestHeaders.Clear();
            cliente?.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            
            HttpResponseMessage mensaje = await cliente?.PostAsync("api/reportes/", data)!;
            
            System.Console.WriteLine(mensaje.ToString());

            if(mensaje.IsSuccessStatusCode){
                return RedirectToAction("HomepageAnimalista", "Homepage");
            }else{
                return RedirectToAction("ErrorPagina", "Home");
            }

        }catch(Exception ex){
            return RedirectToAction("ErrorPagina", "Home");
        }

    }

}

Views/ManejoReporte/EditReporte.cshtml
@model NuevoHogar.ModeloDTO.ReporteDTO

@{
    ViewData["Title"] = "Edita tu Reporte";
}

<center><h1>Formulario de Edicion del Reporte</h1></center>
<center><h4>Edita tu Reporte</h4></center>

<div class="form-vertical">
    <div class="form-inline">
        <div class="container">
            <form class="form-inline" asp-action="GuardarCuentaBtn" asp-controller="ManejoReporte">
                <div class="mx-auto form-group">
                    <div asp-validation-summary="ModelOnly"></div>
                    <p>Ubicacion</p>
                    <div asp-validation-for="ubicacion" class="text-danger"></div>
                    <input type="text" asp-for="ubicacion" class="form-control" placeholder="Ingresa la ubicacion" id="txtUbicacion">
                    <div asp-validation-summary="ModelOnly"></div>
                    <p>Descripcion</p>
                    <div asp-validation-for="descripcion" class="text-danger"></div>
                    <input type="text" asp-for="descripcion" class="form-control" placeholder="Ingresa una descripcion" id="txtDescripcion">
                    
                    <div asp-validation-summary="ModelOnly"></div>
                    <p>Fecha</p>
                    <div asp-validation-for="fecha" class="text-danger"></div>
                    <input type="date" asp-for="fecha" class="form-control" id="dpFecha" placeholder="Ingresa la fecha del avistamiento" id="txtFecha">
                    
                    <p></p>
                    <input type="submit" class="btn btn-primary b-none ml-2 border-0" value="Generar Reporte">
                </div>
            </form>
        </div>
    </div>
</div>

Views/ManejoReporte/GenerarReporte.cshtml
@model NuevoHogar.ModeloDTO.ReporteDTO

@{
    ViewData["Title"] = "Genera tu Reporte";
}

<center><h1>Formulario Reporte</h1></center>
<center><h4>Llena el formulario para crear tu reporte</h4></center>

<div class="form-vertical">
    <div class="form-inline">
        <div class="container">
            <form class="form-inline" asp-action="GenerarReporteBtn" asp-controller="ManejoReporte">
                <div class="mx-auto form-group">
                    <div asp-validation-summary="ModelOnly"></div>
                    <p>Ubicacion</p>
                    <div asp-validation-for="ubicacion" class="text-danger"></div>
                    <input type="text" asp-for="ubicacion" class="form-control" placeholder="Ingresa la ubicacion" required>
                    
                    <div asp-validation-summary="ModelOnly"></div>
                    <p>Descripcion</p>
                    <div asp-validation-for="descripcion" class="text-danger"></div>
                    <input type="text" asp-for="descripcion" class="form-control" placeholder="Ingresa una descripcion" required>
                    
                    <div asp-validation-summary="ModelOnly"></div>
                    <p>Fecha</p>
                    <div asp-validation-for="fecha" class="text-danger"></div>
                    <input type="date" asp-for="fecha" class="form-control" id="dpFecha" placeholder="Ingresa la fecha del avistamiento" required>
                    
                    <p></p>
                    <input type="submit" class="btn btn-primary b-none ml-2 border-0" value="Generar Reporte">
                </div>
            </form>
        </div>
    </div>
</div>

Views/ManejoReporte/ListaReportes.cshtml
@model List<NuevoHogar.ModeloDTO.Reporte2DTO>

@{
    ViewData["Title"] = "Lista de Reportes";
}

<center><h1>Reportes de la Comunidad</h1></center>

<div class="form-group">
    <p></p>
    <input type="button" value="Mostrar mis Reportes" onclick="location.href='@Url.Action("ListaReportesUsuario", "ManejoReporte")';"/>
    <p></p>

    <table class= "table table-bordered">
        <thead>
            <tr>
                <th>Fecha</th>
                <th>Ubicacion</th>
                <th>Descripcion</th>
                <th>Usuario</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var reporte in Model){
                <tr>
                    <td>@reporte.fecha</td>
                    <td>@reporte.ubicacion</td>
                    <td>@reporte.descripcion</td>
                    <td>@reporte.nombreUsuario</td>
                </tr>
            }
        </tbody>
    </table>    
 </div>

Views/ManejoReporte/ListaReportesUsuario.cshtml
@model List<NuevoHogar.ModeloDTO.Reporte2DTO>

@{
    ViewData["Title"] = "Lista de Reportes";
}

<center><h1>Reportes de la Comunidad</h1></center>

<div class="form-group">

    <input type="button" value="Nuevo Reporte" onclick="location.href='@Url.Action("GenerarReporte", "ManejoReporte")';"/>
    
    <p></p>

    <table class= "table table-bordered">
        <thead>
            <tr>
                <th>Fecha</th>
                <th>Ubicacion</th>
                <th>Descripcion</th>
                <th>Usuario</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var reporte in Model){
                <tr>
                    <td>@reporte.fecha</td>
                    <td>@reporte.ubicacion</td>
                    <td>@reporte.descripcion</td>
                    <td>@reporte.nombreUsuario</td>
                    <td>
                        <a asp-action="EditReporte" class="btn btn-warning" asp-controller="ManejoReporte">Editar</a> |
                        <a asp-action="DeleteReporte" class="btn btn-danger" asp-controller="ManejoReporte">Eliminar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>    

    <p></p>

 </div>